name: Simple Pipeline with Skipped Step

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean compile


      # Step 3: Run Snyk Security Scan (skipped for pull requests)
      - name: Run Snyk Security Scan
        if: ${{ github.event_name == 'push' }}
        run: |
          npm install -g snyk
          snyk test

      # Step 4: Build the project
      - name: Build Project
        run: npm run build 

      # Step 5: Run tests
      - name: Run Tests
        run: npm test
